# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  apt_packages:
    - doxygen
    - graphviz
  jobs:
    pre_build:
      - doxygen

sphinx:
  configuration: source/conf.py

commands:
  # 1) Generate the Doxygen XML
  - doxygen Doxyfile
  # 2) Build the Sphinx site
  - sphinx-build -b html docs/ _build/html

formats:
  - pdf

python:
  install:
    - requirements: requirements.txt
